import { useState, useRef, useEffect } from 'react';
import './App.css'
import Header from './components/Header'
import Homex from './components/Homex'
import Homey from './components/Homey';
import Homez from './components/Homez';


function App() {

  return (
    <>
      {/* <Header /> */}
      <Homey />
      {/* <Homez /> */}
      <main className='max-w-screen-xl my-0 mx-auto'>
        <section className="mb-5" id='home'>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Nemo quia debitis at eligendi magnam officia. Lorem ipsum dolor sit amet consectetur, adipisicing elit. Eum sit dolorem neque tempore dolores, fugiat necessitatibus ipsam, cum impedit amet repellendus sapiente nisi consectetur pariatur minima? Voluptates id eveniet modi! Lorem ipsum dolor sit amet consectetur adipisicing elit. Eaque, fugit numquam porro sapiente iste recusandae dolor veniam similique nulla perspiciatis culpa sunt vero repudiandae? A ad dolorum minima molestiae nostrum. Quis praesentium eos quas, itaque voluptas explicabo libero alias nam quidem laboriosam culpa aliquid omnis eum deleniti tempora dignissimos! Quia eius animi alias veritatis nam optio ad libero eum veniam reiciendis eos qui, hic suscipit quos nesciunt tempora aspernatur! Fugiat nobis unde voluptate officiis officia iusto animi voluptates, ullam ex saepe sint assumenda tempora repellat natus sed distinctio amet excepturi deserunt labore quia quae dicta veritatis? Doloremque dolore molestiae dolorum!</section>
        <section className="mb-5" id='about'>Lorem ipsum dolor sit amet consectetur adipisicing elit. Ullam, quia? Est ipsa illum sint id expedita quos totam sed, perspiciatis cumque quidem, mollitia facilis ratione temporibus omnis. Perspiciatis, eius nulla! Odit alias eaque commodi dicta veniam? Minus vitae laborum debitis dolorum tenetur ducimus. Atque aliquid amet earum impedit tempora dolorem inventore sed sint rerum laudantium beatae tenetur et totam nisi, exercitationem, modi sunt commodi vero corporis incidunt fugit saepe id! Voluptates nostrum accusamus suscipit amet tempora. Exercitationem ad, dolorem esse quibusdam unde temporibus! Obcaecati autem nihil atque aspernatur nam ad, et tempore illo itaque repellat quod tenetur, maiores consectetur cumque.</section>
        <section className="mb-5" id='service'>Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatibus sunt placeat dolores soluta blanditiis fugiat voluptas sequi quam hic rerum ipsa suscipit consequatur libero, fugit corporis cum, quasi labore. Architecto eligendi expedita ut, natus, cumque vero sed nesciunt nostrum molestias officia maxime dolorem dolores saepe, harum tempore. Perferendis iusto rem incidunt fugit laboriosam vel fugiat voluptas error? Libero nemo modi alias voluptatibus? Atque, dicta. Expedita modi facere sint illum magni veritatis optio recusandae fugiat consequuntur enim dolores dolorum esse doloremque tenetur, voluptatem ducimus saepe maiores? Odit, sapiente quae dignissimos inventore laborum perspiciatis dolore corporis explicabo. Tempora enim consequuntur esse sed.</section>
        <section className='mt-10' id='expert'>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Magni obcaecati libero, dignissimos animi laudantium incidunt alias, ipsum fuga deleniti in blanditiis fugiat tempore nisi beatae ut laborum veniam deserunt repellat et veritatis magnam? Beatae praesentium eum, nihil repudiandae labore deleniti illum quis earum rerum non animi ipsum inventore doloribus aliquid, libero exercitationem consectetur quasi corporis rem excepturi hic eveniet sed fuga esse. Iure aspernatur unde maiores placeat officia atque at voluptas voluptatibus nam inventore accusantium harum aliquid consequatur ea, voluptatum odio magni facilis recusandae aperiam cum possimus iste! Error debitis suscipit in excepturi facere laudantium fugit, dolorum voluptate pariatur blanditiis qui, odit laborum provident veritatis, unde autem sequi vitae? Facilis, aspernatur in, eligendi alias reprehenderit labore molestias optio quisquam soluta similique animi nihil maxime, natus ut voluptatum. Deserunt eligendi excepturi aut, facilis nostrum recusandae omnis! Adipisci eum amet velit, nulla eveniet, dolore voluptatum modi, accusamus exercitationem dolorem accusantium! Ea, dignissimos? Earum eius dolor sunt magni esse quis expedita alias quia soluta pariatur. Magni mollitia, dolore nisi nulla, dolores quasi voluptate aliquid neque perspiciatis harum voluptatibus sit laboriosam earum delectus iure alias modi error esse quo fugiat, iste tempore! Labore ipsum pariatur optio facere quibusdam. Sint dolor illo quibusdam voluptatem magni.</section>
        <section className='mt-10' id='works'>Lorem ipsum dolor sit amet consectetur adipisicing elit. Error, id necessitatibus! Tenetur, quis, commodi consectetur dolore ullam exercitationem consequatur rerum voluptatem cumque id ad fugiat fuga adipisci, cum hic qui amet aperiam modi enim dolorum. Dolore architecto culpa laboriosam cupiditate animi. Adipisci veniam accusantium temporibus voluptate eaque itaque officiis, rerum sequi natus aut omnis, nemo autem recusandae! Deleniti odio alias similique reprehenderit? Tempore mollitia, consequuntur maiores sequi ullam veritatis inventore rem, culpa sint temporibus exercitationem maxime enim excepturi? Eveniet rerum qui amet minima architecto consequuntur asperiores omnis sapiente quibusdam voluptates fugit quidem eligendi quasi consectetur facilis, hic recusandae necessitatibus! Dolorum, nesciunt explicabo assumenda officiis numquam repellendus iste voluptate sunt perferendis quaerat, reiciendis natus pariatur minus, tenetur nam accusamus mollitia repudiandae. Aspernatur quas mollitia ipsam accusantium error. Fuga, eos! Reiciendis fugiat ex molestiae animi sunt fugit quis dignissimos cupiditate blanditiis velit! Commodi minima quos eius praesentium ea perspiciatis dignissimos nostrum officia! Iste molestias nobis deleniti veritatis illum sit minima blanditiis facere dolore vero error voluptas reiciendis laboriosam nostrum esse porro hic, rerum illo. Aliquid beatae, impedit nesciunt ab cum harum, modi odit ullam cumque ea, ipsam est? Temporibus a nisi aliquam vero consequatur? Nobis autem a molestiae ab unde alias saepe!</section>
        <section className='mt-10' id='blog'>Lorem ipsum dolor sit amet consectetur adipisicing elit. Sed laboriosam sit accusantium odit? Quaerat ut dolore distinctio optio dolorem nobis, ducimus quisquam accusamus amet numquam magnam quis sed, quia vero sapiente possimus voluptatum odio dicta non autem beatae. Ea blanditiis molestiae nihil maiores consequuntur error excepturi nisi, amet minima laboriosam natus sit possimus earum quaerat, quia doloribus necessitatibus eius odit et, adipisci eligendi consequatur nam? Nobis dolore dicta reiciendis? Nihil sequi doloribus molestias. Veritatis, quisquam, amet voluptatem vel commodi tenetur quidem magni molestiae blanditiis totam facilis nemo libero et dicta obcaecati illo rerum numquam maiores enim eius? Explicabo, natus voluptate! Numquam qui temporibus aut nam suscipit provident dignissimos tenetur, quidem ipsum omnis veniam esse, atque reprehenderit molestiae voluptatum rerum culpa quo repudiandae aliquam explicabo sed error eos similique. Maxime sint, a nobis id harum quis atque ex repudiandae ea aliquid accusamus laudantium, fugiat minima animi nam sequi in quas. Nihil autem, at unde harum recusandae, cum atque quaerat maiores blanditiis dolorum sint illum dolore eligendi vitae ipsam nostrum quis cumque necessitatibus laboriosam asperiores molestiae illo perspiciatis numquam. Ad consequuntur illum quis vel alias reprehenderit ipsum officia dolorum laudantium reiciendis suscipit at, ipsa ratione sapiente labore quaerat vitae aut debitis facilis.</section>
        <section className='mt-10' id='contact'>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Dolorum et aut optio. Sunt autem minima, delectus sed unde libero voluptates repudiandae laborum sint, illo modi! Reiciendis odio animi incidunt ratione, iste consequatur fugiat recusandae placeat! Assumenda cupiditate voluptates voluptate perspiciatis reiciendis ducimus ut, illum non obcaecati est perferendis? Fugiat consequatur, perspiciatis quis voluptatibus, veritatis quo vel doloremque corrupti laboriosam iste sapiente a vero aliquam modi voluptate, recusandae optio quidem quam saepe maiores sit odit? Fugit fugiat, itaque laudantium quidem, error optio nostrum, fuga omnis ut soluta incidunt qui ipsum inventore quas alias. Vero voluptate provident neque amet ex, voluptas facere nemo itaque animi, nihil quibusdam cupiditate officiis atque quod aut, natus dignissimos? Quisquam quae tempora dicta voluptatem, dolor minima laboriosam laborum officiis quia aut rerum iste error labore, voluptates laudantium officia deleniti fuga molestias totam quis tempore. In, aliquid rerum omnis at, nisi earum facere nam vel consequatur asperiores, sapiente veritatis sit aspernatur quis ea accusamus doloremque inventore iusto minima? Sequi repellendus nobis quam eos temporibus distinctio autem nostrum hic sit. Aspernatur dolor doloremque minus eius? Quasi sed suscipit alias esse id assumenda temporibus, qui quas ea. Dolore culpa quasi ab veritatis deleniti quisquam accusamus quod excepturi vitae, amet illum.</section>
      </main>
    </>
  )
}

export default App
